"""Initial migration with all tables

Revision ID: eda9b531b265
Revises: 
Create Date: 2025-06-13 21:58:01.286870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda9b531b265'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('paystack_customer_code', sa.String(length=100), nullable=True),
    sa.Column('paystack_subscription_code', sa.String(length=100), nullable=True),
    sa.Column('free_generations_used', sa.Integer(), nullable=False),
    sa.Column('monthly_generations_allowed', sa.Integer(), nullable=False),
    sa.Column('monthly_generations_used', sa.Integer(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('is_founder', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('generated_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('caption_text', sa.Text(), nullable=False),
    sa.Column('visual_suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_content')
    op.drop_table('user')
    # ### end Alembic commands ###
